POST http://localhost:8080/sign-up
Content-Type: application/json

{
    "email":"test5@gmail.com",
    "password": "Test@1234",
    "confirmPassword":"Test@1234",
    "firstName":"Werna",
    "lastName" :"Tester2",
    "userName":"Werna",
    "referredBy" :"REF-GO-OZUI12"
}